[build]
  base = "."  # Root directory where `package.json` is located
  command = "npm run build"
  publish = "build" 

[build.environment]
  NODE_ENV = "production"
  API_KEY = "nfp_xWr9fAHrqp9NB2KmtAsh8yKgYdsaFzPud998"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Custom-Header = "value"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    baseUrl = "https://example.com"  # Use the correct base URL for your site
    buildDir = "build"               # The directory where build files are output
    filePath = "sitemap.xml"         # The file where the sitemap should be written
    exclude = []                     # List of paths to exclude from the sitemap
    prettyURLs = true                # Set to true if you want pretty URLs
    changeFreq = "daily"             # Frequency of changes to pages
    priority = 0.5                   # Priority of the pages
    trailingSlash = false            # Add a trailing slash to URLs
    urlPrefix = ""                   # URL prefix to add to all URLs in the sitemap
