[build]
  base = "."  # Root directory where `package.json` is located
  command = "npm run build"
  publish = "build" 

[build.environment]
  NODE_ENV = "production"
  API_KEY = "nfp_xWr9fAHrqp9NB2KmtAsh8yKgYdsaFzPud998"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Custom-Header = "value"

[context.production.environment]
  NODE_ENV = "production"

[context.deploy-preview.environment]
  NODE_ENV = "development"

[[plugins]]
  package = "@netlify/plugin-sitemap"
  [plugins.inputs]
    site_url = "https://example.com"
